### ISSUE TITLE
Maintenance Status

### ISSUE THREAD

**Issue by Tonkpils** [levicook/glitch#5]
What's the status on maintenance of this tool? 

Seems like the last commit was over a year ago https://github.com/levicook/glitch/commit/a77c6c2ba02b632117897cbf9fa35f718608d6d5 and some newer PRs that resolve a valid issues have not been addressed.

@levicook could you give us some insight or if you need help maintaining this project, I'm sure a couple of people would be glad to help out.

**Comment by levicook** [comment]
I overlooked the last PR - sorry about that. Didn't mean to cause confusion. I'm generally open to pull requests.

**Comment by levicook** [comment]
I only saw one PR--you're note described more than one. Am I missing something?

**Comment by Tonkpils** [comment]
There's still #3 if you could take a look at it. Thanks for reviewing them! Appreciate the work you've put into this.

**Comment by levicook** [comment]
@Tonkpils thanks for calling these to my attention. Didn't mean to ignore anyone -- definitely happy to see the tool improve.
